app: tooling-s3-sqs
service: tooling-s3-sqs

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  environment:
    BUCKET_NAME: arquivos-009-gprizzon
    SQS_QUEUE: file-handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
        - sqs:CreateQueue
        - sqs:ReceiveMessage
      Resource: ${self:custom.sqsArn}
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  sqsArn:
    Fn::GetAtt:
      - SQSQueue
      - Arn
  localstack:
    stages:
      - local
    autostart: false # desabilita o localstack quando fizer deploy
  serverless-offline:
    useChildProcess: true

package:
  individually: true
  excludeDevDependencies: true

functions:
  s3Listener:
    handler: src/index.s3Listener
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
  sqsListener:
    handler: src/index.sqsListener
    events:
      - sqs:
          batchSize: 1
          arn: ${self:custom.sqsArn}

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.SQS_QUEUE}
        VisibilityTimeout: 60
